steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/cybersorted/cybersorted-mcp:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/cybersorted/cybersorted-mcp:latest"
      - "."

  # Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/cybersorted/cybersorted-mcp"

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "cybersorted-mcp-${_ENVIRONMENT}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/cybersorted/cybersorted-mcp:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "5"
      - "--set-env-vars"
      - "ENVIRONMENT=${_ENVIRONMENT},GCP_PROJECT=${PROJECT_ID},FIRESTORE_DATABASE=database-uk-${_ENVIRONMENT}"
      - "--set-secrets"
      - "STRIPE_SECRET_KEY=stripe-mcp-secret-key:latest"
      - "--allow-unauthenticated"

substitutions:
  _REGION: europe-west1
  _ENVIRONMENT: dev

options:
  logging: CLOUD_LOGGING_ONLY
